### ISSUE TITLE
Migrating to meteor(ite) v0.9.0

### ISSUE THREAD

**Issue by bkuri** [hharnisc/meteor-accounts-admin-ui-bootstrap-3#22]
Running `mrt migrate-app` produces the following error:

```
Updating all references to packages in .meteor/packages
Error: The version 0.3.5 of package accounts-ui-bootstrap-3 has not yet been migrated

If you want to continue, remove the offending package from smart.json, run 'mrt install', and try again.

After you have successfully migrated, you can add it back but note:
  You will NOT receive further updates to this package.

See https://hackpad.com/Migrating-Apps-UfPrM192vSQ for more information.
```

**Comment by bkuri** [comment]
FYI: https://hackpad.com/Add-Meteor-0.9-support-for-your-Existing-Packages-P0R7y1PiXlu

**Comment by hharnisc** [comment]
Ran into some issues migrating - I've posted some detail on the meteor-talk group: https://groups.google.com/forum/#!topic/meteor-talk/dFNevI7SJ24

The package seems to have made it into the mass update as `mrt:accounts-admin-ui-bootstrap-3`
So that might keep you running until I get this figured out.

**Comment by manybothans** [comment]
+1. Cool, glad you're on it :) . FYI, the mass update version says "INCOMPATIBLE WITH METEOR 0.9.0 OR LATER"

**Comment by hharnisc** [comment]
I've got this fixed, and tested on a sample app. I'll close this out, but let's reopen it if the fixes do work for you.
